{
  "openapi": "3.0.0",
  "info": {
    "title": "BSV ARC",
    "version": "1.0.0",
    "license": {
      "name": "Open BSV Licence",
      "url": "https://bitcoinassociation.net/open-bsv-license/"
    }
  },
  "servers": [
    {
      "url": "https://tapi.taal.com/arc"
    }
  ],
  "paths": {
    "/v1/policy": {
      "get": {
        "operationId": "GET policy",
        "tags": [
          "Arc"
        ],
        "summary": "Get the policy settings",
        "description": "This endpoint returns the policy settings.",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PolicyResponse"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/NotAuthorized"
          }
        }
      }
    },
    "/v1/tx/{txid}": {
      "get": {
        "operationId": "GET transaction status",
        "tags": [
          "Arc"
        ],
        "summary": "Get transaction status.",
        "description": "This endpoint is used to get the current status of a previously submitted transaction.",
        "parameters": [
          {
            "name": "txid",
            "in": "path",
            "description": "The transaction ID (32 byte hash) hex string",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionStatus"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/NotAuthorized"
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFound"
                }
              }
            }
          },
          "409": {
            "description": "Generic error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorGeneric"
                }
              }
            }
          }
        }
      }
    },
    "/v1/tx": {
      "post": {
        "operationId": "POST transaction",
        "tags": [
          "Arc"
        ],
        "summary": "Submit a transaction.",
        "description": "This endpoint is used to send a raw transaction to a miner for inclusion in the next block that the miner creates.  The header parameters can be used to override the global settings in your Arc dashboard for these transactions.",
        "parameters": [
          {
            "$ref": "#/components/parameters/callbackUrl"
          },
          {
            "$ref": "#/components/parameters/skipFeeValidation"
          },
          {
            "$ref": "#/components/parameters/skipScriptValidation"
          },
          {
            "$ref": "#/components/parameters/skipTxValidation"
          },
          {
            "$ref": "#/components/parameters/callbackToken"
          },
          {
            "$ref": "#/components/parameters/merkleProof"
          },
          {
            "$ref": "#/components/parameters/waitForStatus"
          }
        ],
        "requestBody": {
          "required": true,
          "description": "Transaction hex string",
          "content": {
            "text/plain": {
              "schema": {
                "type": "string",
                "example": "<transaction hex string>"
              }
            },
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TransactionRequest"
              }
            },
            "application/octet-stream": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionResponse"
                },
                "examples": {
                  "mined": {
                    "summary": "Transaction mined",
                    "value": {
                      "blockHash": "0000000000000aac89fbed163ed60061ba33bc0ab9de8e7fd8b34ad94c2414cd",
                      "blockHeight": 736228,
                      "extraInfo": "",
                      "status": 200,
                      "timestamp": "2023-03-09T12:03:48.382910514Z",
                      "title": "OK",
                      "txStatus": "MINED",
                      "txid": "b68b064b336b9a4abdb173f3e32f27b38a222cb2102f51b8c92563e816b12b4a",
                      "merklePath": "fe54251800020400028d97f9ebeddd9f9aa8e0e953b3a76f316298ab05e9834aa811716e9d397564e501025f64aa8e012e26a5c5803c9f94d1c2c8ea68ecef1415011e1c2e26b9c966b6ad02021f5fa39607ca3b48d53c902bd5bb4bbf6a7ac99cf9fda45cc21b71e6e2f7889603024a2bb116e86325c9b8512f10b22c228ab3272fe3f373b1bd4a9a6b334b068bb602000061793b278303101a1390ceae5a713de0eabd9cda63702fe84c928970acf7c45e0100a567e3d066e38638b27897559302eabc85eb69b202c2e86d4338bab73008f460"
                    }
                  },
                  "mempool": {
                    "summary": "Transaction in mempool",
                    "value": {
                      "blockHash": "",
                      "blockHeight": 0,
                      "extraInfo": "",
                      "status": 200,
                      "timestamp": "2023-03-09T12:03:48.382910514Z",
                      "title": "OK",
                      "txStatus": "SEEN_ON_NETWORK",
                      "txid": "c0d6fce714e4225614f000c6a5addaaa1341acbb9c87115114dcf84f37b945a6",
                      "merklePath": ""
                    }
                  },
                  "error": {
                    "summary": "Invalid outputs",
                    "value": {
                      "detail": "Transaction is invalid because the outputs are non-existent or invalid",
                      "extraInfo": "arc error 463: arc error 463: transaction output 0 satoshis is invalid",
                      "instance": null,
                      "status": 463,
                      "title": "Invalid outputs",
                      "txid": "a0d69a2dfad710770ed282cce316c5792f6101a68046a263a17a1ae02676015e",
                      "type": "https://bitcoin-sv.github.io/arc/#/errors?id=_463\""
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequest"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/NotAuthorized"
          },
          "409": {
            "description": "Generic error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorGeneric"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable entity - with IETF RFC 7807 Error object",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "460": {
            "description": "Not extended format",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorTxFormat"
                }
              }
            }
          },
          "461": {
            "description": "Malformed transaction",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnlockingScripts"
                }
              }
            }
          },
          "462": {
            "description": "Invalid inputs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorInputs"
                }
              }
            }
          },
          "463": {
            "description": "Malformed transaction",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMalformed"
                }
              }
            }
          },
          "464": {
            "description": "Invalid outputs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorOutputs"
                }
              }
            }
          },
          "465": {
            "description": "Fee too low",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorFee"
                }
              }
            }
          }
        }
      }
    },
    "/v1/txs": {
      "post": {
        "operationId": "POST transactions",
        "tags": [
          "Arc"
        ],
        "summary": "Submit multiple transactions.",
        "description": "This endpoint is used to send multiple raw transactions to a miner for inclusion in the next block that the miner creates. The header parameters can be used to override the global settings in your Arc dashboard for these transactions.",
        "parameters": [
          {
            "$ref": "#/components/parameters/callbackUrl"
          },
          {
            "$ref": "#/components/parameters/skipFeeValidation"
          },
          {
            "$ref": "#/components/parameters/skipScriptValidation"
          },
          {
            "$ref": "#/components/parameters/skipTxValidation"
          },
          {
            "$ref": "#/components/parameters/callbackToken"
          },
          {
            "$ref": "#/components/parameters/merkleProof"
          },
          {
            "$ref": "#/components/parameters/waitForStatus"
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "text/plain": {
              "schema": {
                "type": "string",
                "example": "<transaction hex string>\n<transaction hex string>"
              }
            },
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/TransactionRequest"
                }
              }
            },
            "application/octet-stream": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Transaction status",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TransactionResponses"
                },
                "examples": {
                  "mined": {
                    "summary": "Transaction mined",
                    "value": [
                      {
                        "blockHash": "0000000000000aac89fbed163ed60061ba33bc0ab9de8e7fd8b34ad94c2414cd",
                        "blockHeight": 761868,
                        "extraInfo": "",
                        "status": 200,
                        "timestamp": "2023-03-09T12:03:48.382910514Z",
                        "title": "OK",
                        "txStatus": "MINED",
                        "txid": "b68b064b336b9a4abdb173f3e32f27b38a222cb2102f51b8c92563e816b12b4a",
                        "merklePath": "fe54251800020400028d97f9ebeddd9f9aa8e0e953b3a76f316298ab05e9834aa811716e9d397564e501025f64aa8e012e26a5c5803c9f94d1c2c8ea68ecef1415011e1c2e26b9c966b6ad02021f5fa39607ca3b48d53c902bd5bb4bbf6a7ac99cf9fda45cc21b71e6e2f7889603024a2bb116e86325c9b8512f10b22c228ab3272fe3f373b1bd4a9a6b334b068bb602000061793b278303101a1390ceae5a713de0eabd9cda63702fe84c928970acf7c45e0100a567e3d066e38638b27897559302eabc85eb69b202c2e86d4338bab73008f460"
                      }
                    ]
                  },
                  "added": {
                    "summary": "Transaction in mempool",
                    "value": [
                      {
                        "blockHash": "",
                        "blockHeight": 0,
                        "extraInfo": "",
                        "status": 200,
                        "timestamp": "2023-03-09T12:03:48.382910514Z",
                        "title": "OK",
                        "txStatus": "SEEN_ON_NETWORK",
                        "txid": "c0d6fce714e4225614f000c6a5addaaa1341acbb9c87115114dcf84f37b945a6",
                        "merklePath": ""
                      }
                    ]
                  },
                  "error": {
                    "summary": "Invalid outputs",
                    "value": [
                      {
                        "detail": "Transaction is invalid because the outputs are non-existent or invalid",
                        "extraInfo": "arc error 463: arc error 463: transaction output 0 satoshis is invalid",
                        "instance": null,
                        "status": 463,
                        "title": "Invalid outputs",
                        "txid": "a0d69a2dfad710770ed282cce316c5792f6101a68046a263a17a1ae02676015e",
                        "type": "https://bitcoin-sv.github.io/arc/#/errors?id=_463"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequest"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/NotAuthorized"
          },
          "409": {
            "description": "Generic error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorGeneric"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable entity - with IETF RFC 7807 Error object",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "460": {
            "description": "Not extended format",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorTxFormat"
                }
              }
            }
          },
          "461": {
            "description": "Malformed transaction",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnlockingScripts"
                }
              }
            }
          },
          "462": {
            "description": "Invalid inputs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorInputs"
                }
              }
            }
          },
          "463": {
            "description": "Malformed transaction",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorMalformed"
                }
              }
            }
          },
          "464": {
            "description": "Invalid outputs",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorOutputs"
                }
              }
            }
          },
          "465": {
            "description": "Fee too low",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorFee"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CommonResponse": {
        "type": "object",
        "required": [
          "timestamp"
        ],
        "description": "Common response object",
        "properties": {
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "nullable": false
          }
        }
      },
      "ChainInfo": {
        "type": "object",
        "description": "Chain info",
        "properties": {
          "blockHash": {
            "type": "string",
            "nullable": false,
            "example": "00000000000000000854749b3c125d52c6943677544c8a6a885247935ba8d17d",
            "description": "Block hash"
          },
          "blockHeight": {
            "type": "integer",
            "format": "uint64",
            "nullable": false,
            "example": 782318,
            "description": "Block height"
          }
        }
      },
      "PolicyResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonResponse"
          },
          {
            "type": "object",
            "required": [
              "policy"
            ],
            "properties": {
              "policy": {
                "$ref": "#/components/schemas/Policy"
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "Policy": {
        "type": "object",
        "required": [
          "maxscriptsizepolicy",
          "maxtxsigopscountspolicy",
          "maxtxsizepolicy",
          "miningFee"
        ],
        "properties": {
          "maxscriptsizepolicy": {
            "type": "integer",
            "format": "uint64",
            "nullable": false,
            "description": "Maximum script size [bytes]"
          },
          "maxtxsigopscountspolicy": {
            "type": "integer",
            "format": "uint64",
            "nullable": false,
            "description": "Maximum number of signature operations"
          },
          "maxtxsizepolicy": {
            "type": "integer",
            "format": "uint64",
            "nullable": false,
            "description": "Maximum transaction size [bytes]"
          },
          "miningFee": {
            "$ref": "#/components/schemas/FeeAmount",
            "description": "Mining fee"
          }
        },
        "additionalProperties": false,
        "example": {
          "maxscriptsizepolicy": 500000,
          "maxtxsigopscountspolicy": 4294967295,
          "maxtxsizepolicy": 10000000,
          "miningFee": {
            "satoshis": 1,
            "bytes": 1000
          }
        }
      },
      "FeeAmount": {
        "type": "object",
        "required": [
          "satoshis",
          "bytes"
        ],
        "properties": {
          "satoshis": {
            "type": "integer",
            "format": "uint64",
            "description": "Amount in Satoshis"
          },
          "bytes": {
            "type": "integer",
            "format": "uint64",
            "description": "Number of bytes"
          }
        },
        "additionalProperties": false
      },
      "TransactionRequest": {
        "type": "object",
        "required": [
          "rawTx"
        ],
        "properties": {
          "rawTx": {
            "type": "string",
            "nullable": false,
            "description": "Raw hex string"
          }
        },
        "example": {
          "rawTx": "<transaction hex string>"
        }
      },
      "TransactionResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonResponse"
          },
          {
            "$ref": "#/components/schemas/ChainInfo"
          },
          {
            "$ref": "#/components/schemas/TransactionDetails"
          },
          {
            "type": "object",
            "required": [
              "txid",
              "txStatus",
              "extraInfo"
            ],
            "properties": {
              "txid": {
                "type": "string",
                "nullable": false,
                "description": "Transaction ID in hex"
              },
              "txStatus": {
                "type": "string",
                "nullable": false,
                "description": "Transaction status"
              },
              "merklePath": {
                "type": "string",
                "nullable": true,
                "description": "Transaction Merkle path as a hex string in  BUMP format [BRC-74](https://brc.dev/74)"
              },
              "extraInfo": {
                "type": "string",
                "nullable": true,
                "description": "Extra info"
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "TransactionStatus": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonResponse"
          },
          {
            "$ref": "#/components/schemas/ChainInfo"
          },
          {
            "type": "object",
            "required": [
              "txid",
              "status"
            ],
            "properties": {
              "txid": {
                "type": "string",
                "nullable": false,
                "example": "7927233d10dacd5606cee5bf0b28668fc191e730029ace4c7fc40ede59a2825e",
                "description": "Transaction ID in hex"
              },
              "merklePath": {
                "type": "string",
                "nullable": true,
                "description": "Transaction Merkle path as a hex string in BUMP format [BRC-74](https://brc.dev/74)"
              },
              "txStatus": {
                "type": "string",
                "nullable": false,
                "description": "Transaction status",
                "example": "MINED"
              },
              "extraInfo": {
                "type": "string",
                "nullable": true,
                "description": "Extra information about the transaction",
                "example": null
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "TransactionResponses": {
        "allOf": [
          {
            "$ref": "#/components/schemas/CommonResponse"
          },
          {
            "$ref": "#/components/schemas/ChainInfo"
          },
          {
            "type": "object",
            "properties": {
              "transactions": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/TransactionDetails"
                    },
                    {
                      "$ref": "#/components/schemas/Error"
                    }
                  ]
                }
              }
            },
            "additionalProperties": false
          }
        ]
      },
      "TransactionSubmitStatus": {
        "type": "object",
        "required": [
          "status",
          "title"
        ],
        "description": "Transaction submit status",
        "properties": {
          "status": {
            "type": "integer",
            "format": "int",
            "example": 201,
            "nullable": false,
            "description": "Status"
          },
          "title": {
            "type": "string",
            "description": "Title",
            "example": "Added to mempool",
            "nullable": false
          }
        }
      },
      "TransactionDetails": {
        "type": "object",
        "description": "Transaction details",
        "required": [
          "txid"
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/TransactionSubmitStatus"
          },
          {
            "type": "object",
            "properties": {
              "txid": {
                "type": "string",
                "description": "Transaction ID in hex",
                "example": "6bdbcfab0526d30e8d68279f79dff61fb4026ace8b7b32789af016336e54f2f0",
                "nullable": false
              },
              "merklePath": {
                "type": "string",
                "nullable": true,
                "description": "Transaction Merkle path as a hex string in BUMP format [BRC-74](https://brc.dev/74)"
              },
              "txStatus": {
                "type": "string",
                "enum": [
                  "UNKNOWN",
                  "RECEIVED",
                  "STORED",
                  "ANNOUNCED_TO_NETWORK",
                  "REQUESTED_BY_NETWORK",
                  "SENT_TO_NETWORK",
                  "SEEN_ON_NETWORK",
                  "MINED",
                  "CONFIRMED",
                  "REJECTED"
                ],
                "description": "Transaction status",
                "example": "ACCEPTED",
                "nullable": false
              },
              "extraInfo": {
                "type": "string",
                "description": "Extra information about the transaction",
                "example": "Transaction is not valid",
                "nullable": true
              }
            },
            "example": {
              "blockHash": "",
              "blockHeight": 0,
              "extraInfo": "",
              "status": 200,
              "timestamp": "2023-03-09T12:03:48.382910514Z",
              "title": "OK",
              "txStatus": "SEEN_ON_NETWORK",
              "txid": "c0d6fce714e4225614f000c6a5addaaa1341acbb9c87115114dcf84f37b945a6",
              "merklePath": "0000"
            }
          }
        ]
      },
      "Error": {
        "description": "An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).",
        "oneOf": [
          {
            "$ref": "#/components/schemas/ErrorUnlockingScripts"
          },
          {
            "$ref": "#/components/schemas/ErrorInputs"
          },
          {
            "$ref": "#/components/schemas/ErrorMalformed"
          },
          {
            "$ref": "#/components/schemas/ErrorFrozenPolicy"
          },
          {
            "$ref": "#/components/schemas/ErrorFrozenConsensus"
          }
        ]
      },
      "ErrorBadRequest": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_400"
              },
              "title": {
                "example": "Bad request"
              },
              "status": {
                "example": 400
              },
              "detail": {
                "example": "The request seems to be malformed and cannot be processed"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/1234556"
              }
            }
          }
        ]
      },
      "ErrorNotFound": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_404"
              },
              "title": {
                "example": "Not found"
              },
              "status": {
                "example": 404
              },
              "detail": {
                "example": "The requested resource could not be found"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/1234556"
              }
            }
          }
        ]
      },
      "ErrorGeneric": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_409"
              },
              "title": {
                "example": "Generic error"
              },
              "status": {
                "example": 409
              },
              "detail": {
                "example": "Transaction could not be processed"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/1234556"
              }
            }
          }
        ]
      },
      "ErrorTxFormat": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_460"
              },
              "title": {
                "example": "Not extended format"
              },
              "status": {
                "example": 460
              },
              "detail": {
                "example": "Transaction is not in extended format, missing input scripts"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/1234556"
              }
            }
          }
        ]
      },
      "ErrorUnlockingScripts": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_461"
              },
              "title": {
                "example": "Malformed transaction"
              },
              "status": {
                "example": 461
              },
              "detail": {
                "example": "Transaction is malformed and cannot be processed"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorInputs": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_462"
              },
              "title": {
                "example": "Invalid inputs"
              },
              "status": {
                "example": 462
              },
              "detail": {
                "example": "Transaction is invalid because the inputs are non-existent or spent"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorMalformed": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_463"
              },
              "title": {
                "example": "Malformed transaction"
              },
              "status": {
                "example": 463
              },
              "detail": {
                "example": "Transaction is malformed and cannot be processed"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorOutputs": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_464"
              },
              "title": {
                "example": "Invalid outputs"
              },
              "status": {
                "example": 464
              },
              "detail": {
                "example": "Transaction is invalid because the outputs are non-existent or invalid"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorFee": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_465"
              },
              "title": {
                "example": "Fee too low"
              },
              "status": {
                "example": 465
              },
              "detail": {
                "example": "The fees are too low"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorConflict": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_466"
              },
              "title": {
                "example": "Conflicting tx found"
              },
              "status": {
                "example": 466
              },
              "detail": {
                "example": "Transaction is valid, but there is a conflicting tx in the block template"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123453"
              }
            }
          }
        ]
      },
      "ErrorFrozenPolicy": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_471"
              },
              "title": {
                "example": "Input Frozen"
              },
              "status": {
                "example": 471
              },
              "detail": {
                "example": "Input Frozen (blacklist manager policy blacklisted)"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorFrozenConsensus": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorFields"
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "example": "https://bitcoin-sv.github.io/arc/#/errors?id=_472"
              },
              "title": {
                "example": "Input Frozen"
              },
              "status": {
                "example": 472
              },
              "detail": {
                "example": "Input Frozen (blacklist manager consensus blacklisted)"
              },
              "instance": {
                "example": "https://arc.taal.com/errors/123452"
              }
            }
          }
        ]
      },
      "ErrorFields": {
        "type": "object",
        "required": [
          "type",
          "title",
          "status",
          "detail"
        ],
        "properties": {
          "type": {
            "type": "string",
            "description": "Type of error, with link to more information",
            "nullable": false
          },
          "title": {
            "type": "string",
            "description": "Descriptive text for error",
            "nullable": false
          },
          "status": {
            "type": "integer",
            "format": "int",
            "description": "Error code",
            "example": 402,
            "nullable": false
          },
          "detail": {
            "type": "string",
            "description": "Longer description of error",
            "example": "The fee in the transaction is too low to be included in a block.",
            "nullable": false
          },
          "instance": {
            "type": "string",
            "description": "(Optional) Link to actual error on server",
            "nullable": true
          },
          "txid": {
            "type": "string",
            "description": "Transaction ID this error is referring to",
            "nullable": true
          },
          "extraInfo": {
            "type": "string",
            "description": "Optional extra information about the error from the miner",
            "nullable": true
          }
        }
      }
    },
    "responses": {
      "NotAuthorized": {
        "description": "Security requirements failed"
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "description": "Bearer authentication as defined in RFC 6750"
      }
    },
    "parameters": {
      "callbackUrl": {
        "name": "X-CallbackUrl",
        "in": "header",
        "description": "Default double spend and merkle proof notification callback endpoint.",
        "schema": {
          "type": "string"
        }
      },
      "skipFeeValidation": {
        "name": "X-SkipFeeValidation",
        "in": "header",
        "description": "Whether we should skip fee validation or not.",
        "schema": {
          "type": "boolean"
        }
      },
      "skipScriptValidation": {
        "name": "X-SkipScriptValidation",
        "in": "header",
        "description": "Whether we should skip script validation or not.",
        "schema": {
          "type": "boolean"
        }
      },
      "skipTxValidation": {
        "name": "X-SkipTxValidation",
        "in": "header",
        "description": "Whether we should skip overall tx validation or not.",
        "schema": {
          "type": "boolean"
        }
      },
      "callbackToken": {
        "name": "X-CallbackToken",
        "in": "header",
        "description": "Access token for notification callback endpoint. It will be used as a Authorization header for the http callback",
        "schema": {
          "type": "string"
        }
      },
      "merkleProof": {
        "name": "X-MerkleProof",
        "in": "header",
        "description": "Whether to include merkle proofs in the callbacks (true | false).",
        "schema": {
          "type": "string"
        }
      },
      "waitForStatus": {
        "name": "X-WaitForStatus",
        "in": "header",
        "description": "Which status to wait for from the server before returning (2 = RECEIVED, 3 = STORED, 4 = ANNOUNCED_TO_NETWORK, 5 = REQUESTED_BY_NETWORK, 6 = SENT_TO_NETWORK, 7 = ACCEPTED_BY_NETWORK, 8 = SEEN_ON_NETWORK)",
        "schema": {
          "type": "integer"
        }
      }
    }
  },
  "security": [
    {
      "BearerAuth": []
    },
    {
      "Api-Key": []
    },
    {
      "Authorization": []
    }
  ]
}
